// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/add-user-to-team': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/add-user-to-team.post').default>>>>
    }
    '/api/admin/backup/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/backup/create.post').default>>>>
    }
    '/api/admin/backup': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/backup/index.get').default>>>>
    }
    '/api/admin/backup/restore': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/backup/restore.post').default>>>>
    }
    '/api/admin/bulk-create-users': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/bulk-create-users.post').default>>>>
    }
    '/api/admin/delete-user': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/delete-user.delete').default>>>>
    }
    '/api/admin/toggle-role': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/toggle-role.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/chat/conversations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/conversations.get').default>>>>
    }
    '/api/chat/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/messages.get').default>>>>
    }
    '/api/chat/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/send.post').default>>>>
    }
    '/api/debug/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/status.get').default>>>>
    }
    '/api/debug/test-upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/test-upload.post').default>>>>
    }
    '/api/proxy-image': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy-image.get').default>>>>
    }
    '/api/skills': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/skills').default>>>>
    }
    '/api/teams/:id/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/delete.delete').default>>>>
    }
    '/api/teams/:id/images': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/images.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/images.post').default>>>>
    }
    '/api/teams/:id/images/:imageId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/images/[imageId].delete').default>>>>
    }
    '/api/teams/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/index.get').default>>>>
    }
    '/api/teams/:id/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/join.post').default>>>>
    }
    '/api/teams/:id/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/leave.post').default>>>>
    }
    '/api/teams/:id/links': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/links.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/links.post').default>>>>
    }
    '/api/teams/:id/links/:linkId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/links/[linkId].delete').default>>>>
    }
    '/api/teams/:id/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/update.put').default>>>>
    }
    '/api/teams/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/create.post').default>>>>
    }
    '/api/teams': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/index.get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/api/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user.get').default>>>>
    }
    '/api/user/update-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/update-password.post').default>>>>
    }
    '/api/user/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/update.post').default>>>>
    }
    '/api/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}